### ISSUE TITLE
AutoFlight fails to build with opencv 2.4.9

### ISSUE THREAD

**Issue by phaethon** [lukaslaobeyer/AutoFlight_v1#2]
I was trying to build AutoFlight on Ubuntu 15.10. Most likely there are some library version differences as this is what I get trying to compile. I have core.hpp under opencv2/core/core.hpp not as opencv2/core.hpp. If I fix this, then I get next issue with utility.hpp. Did not check further. Which opencv2 version was AutoFlight built with?

AutoFlight_v1/src/autoscript/opencv/asmodules_opencv.cpp:2:28: fatal error: opencv2/core.hpp: No such file or directory
compilation terminated.
CMakeFiles/AutoFlight.dir/build.make:848: recipe for target 'CMakeFiles/AutoFlight.dir/src/autoscript/opencv/asmodules_opencv.cpp.o' failed
make[2]: **\* [CMakeFiles/AutoFlight.dir/src/autoscript/opencv/asmodules_opencv.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/AutoFlight.dir/all' failed
make[1]: **\* [CMakeFiles/AutoFlight.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by phaethon** [comment]
I built it with the latest opencv github version and it worked. It would be nice if Readme included library versions that prebuilt binaries are built with, to save guessing on versions. Especially regarding those libraries, which are available as packages in Ubuntu (opencv, ffmpeg-*).
